### ISSUE TITLE
Cauldron Server Crash

### ISSUE THREAD

**Issue by voidswrath** [eidehua/More-Health-Enhanced#4]
I tried logging into my server however it kicked me for not having one mod. This lead to the server crashing because more health had an issue with me logging out. Cauldron latest version 1403

---- Minecraft Crash Report ----
// You're mean.

Time: 6/26/15 5:26 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
        at com.nohero.morehealth.EventHandlers.PlayerHandlerHelper.savePlayerData(PlayerHandlerHelper.java:210)
        at com.nohero.morehealth.EventHandlers.PlayerHandler.onPlayerLogsout(PlayerHandler.java:77)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_272_PlayerHandler_onPlayerLogsout_PlayerLoggedOutEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:574)
        at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:436)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:945)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.5.0-51-generic
        Java Version: 1.8.0_45, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 397844296 bytes (379 MB) / 987758592 bytes (942 MB) up to 987758592 bytes (942 MB)
        JVM Flags: 3 total; -Xmx1024M -Xms1024M -Xss2M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
        FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 46 mods loaded, 45 mods active
        mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.114.1388} [Forge Mod Loader](cauldron-1.7.10-2.1403.1.49-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{10.13.3.1403} [Minecraft Forge](cauldron-1.7.10-2.1403.1.49-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MobiusCore{1.2.5} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core](malisiscore-1.7.10-0.10.5 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        jewelrycraft2{1.0.11} [Jewelrycraft 2]([1.7.10] Jewelrycraft2-1.0.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        securitycraft{v1.7.4.1} [SecurityCraft]([1.7.10] SecurityCraft v1.7.4.1 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8b %284%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        armourersWorkshop{1.7.10-0.33.0.84} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.33.0.84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        asielib{0.2.7} [asielib](AsieLib-1.7.10-0.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        chisel{2.3.10.37} [Chisel 2](Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        darkcore{0.25} [Dark Core](darkcore-0.25-30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Hats{4.0.1} [Hats](Hats-4.0.1 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        InventoryPets{1.1.2a} [Inventory Pets](inventorypets-1.7.10-1.1.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisisdoors{1.7.10-1.4.3} [Malisis' Doors](malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        mazemod{1.2.5} [Maze Mod](mazemod-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MobProperties{0.4.0} [Mob Properties](MobProperties-1.7.10-0.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        morehealth{6.3} [More Health Forge](More Health Enchanted-1.7.10-6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Morph{0.9.1} [Morph](Morph-Beta-0.9.1 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        cfm{3.4.7} [�9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MutantCreatures{1.4.8} [Mutant Creatures](MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OreSpawn{1.7.10.20.3} [OreSpawn](orespawn-1.7.10-20.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        origin{3.3.0} [Origin](Origin-1.7.10-3.3.0 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        pandorasbox{2.0.1} [Pandora's Box](PandorasBox-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PortalGun{4.0.0-beta-4} [PortalGun](PortalGun-4.0.0-beta-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        SaintsCore{0.8} [Saintscore](SaintsCore-0.9-Minecraft-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways](SoulShards-TOW-1.7.10-0.1-RC9-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        statues{2.1.3} [Statues](statues-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TardisMod{0.985} [Tardis Mod](tardismod-1.7.10-0.985-150.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        transformers{${version}} [Transformers Mod](Transformers-1.7.10-0.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        weepingangels{3.3.2} [Weeping Angels](WeepingAngels-1.7.10-3.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        youtubers{1.7.0} [Youtubers+ Mod](youtubers-1.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 0 / 20; []
        Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by voidswrath** [comment]
more

Client side kick here are teh console for the server and client

Server
http://pastebin.com/WfwS2cxL

Client
http://pastebin.com/Z67Ybcis

**Comment by eidehua** [comment]
Okay so are you saying the server runs fine, it's just clients that connect to the server that has the issue? And normal single player works fine?

**Comment by LemADEC** [comment]
Is that bug still valid?
